## day02~day06
### 一、numpy 和 pandas 是什么</br>

两个都是计算函数包(数学公式 和 常见算法), 前者抽象一些也更基础一些, 核心对象是ndarray. pandas 对二维数组humanize一些, 核心对象是dataframe(series). </br>

**numpy: ndarray = array, pandas: series = ndarray + index, dataframe = n * series**</br>

In [16]:
import numpy as np
import pandas as pd

array = np.random.randint(60, 101, (5, 3))  # 5行3列的二维数组

# ndarray
ndarray = np.array(array)

# index: (行)索引
# data: 限制是一维数组
# series: 一时想不到怎么描述它, 键值对?
series = pd.Series(array[:, 0], index=['狄仁杰', '白起', '李元芳', '苏妲己', '孙尚香'])

# dataframe 数据表格
dataframe = pd.DataFrame(data=array, columns=['语文', '数学', '英语'], index=['狄仁杰', '白起', '李元芳', '苏妲己', '孙尚香'])

ndarray, series, dataframe

(array([[96, 61, 84],
        [97, 78, 62],
        [67, 81, 79],
        [73, 60, 80],
        [83, 81, 88]], dtype=int32),
 狄仁杰    96
 白起     97
 李元芳    67
 苏妲己    73
 孙尚香    83
 dtype: int32,
      语文  数学  英语
 狄仁杰  96  61  84
 白起   97  78  62
 李元芳  67  81  79
 苏妲己  73  60  80
 孙尚香  83  81  88)


### 二、ndarray
数组(矩阵)+函数公式, 它的属性包括:</br>
`size` - 整个数组中的元素的个数, 二维数组就是m*n</br>
`dtype` - 元素的数据类型</br>
    <img src="res/dtype.jpg" style="zoom:50%;"></br>
`ndim` - 数组的维度 --> 一维数组,二维数组,三维数组(比如RGB)</br>
`shape` - 数组的形状 ---> x列x行(不太好记), 实际上就是数组size(外部->内部)</br>
</br>
**创建数组对象**
</br>
通过`array`/`asarray`函数将列表处理成数组对象</br>
通过`arange`函数指定起始值、终止值和跨度创建数组对象</br>
通过`fromstring`/`fromfile`函数从字符串或文件中读取数据创建数组对象</br>
</br>
**索引**
</br>
图1：二维数组的普通索引
</br>
<img src="res/ndarray-index.png" style="zoom:60%;"></br>
图2：二维数组的切片索引</br>
<img src="res/ndarray-slice.png" style="zoom:60%;"></br>



In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

array1 = np.array([1, 2, 3, 4, 5, 6])
array2 = np.array([[1, 2, 3], [4, 5, 6]])
array3 = np.arange(1, 10)
array4 = np.arange(1, 100, 3)
array5 = np.fromstring('1, 11, 111, 2, 22, 222', sep=',', dtype='i8')
array6 = np.fromfile('res/prime.txt', dtype='i8', sep='\n', count=15)

In [14]:
array1.ndim, array2.ndim, '$$$', array1.shape, array2.shape

(1, 2, '$$$', (6,), (2, 3))

In [15]:
array3, array4, array5, array6

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
        52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]),
 array([  1,  11, 111,   2,  22, 222]),
 array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]))

### 三、DataFrame

- `Series`：表示一维的数据。跟一维数组的区别在于每条数据都有对应的索引，处理数据的方法比`ndarray`更为丰富。
- `DataFrame`：表示二维的数据。跟二维数组相比，`DataFrame`有行索引和列索引，而且提供了100+方法来处理数据。
- `Index`：为`Series`和`DataFrame`提供索引服务。


In [18]:
import numpy as np
import pandas as pd

ser1 = pd.Series(data=[120, 380, 250, 360], index=['一季度', '二季度', '三季度', '四季度'])
ser2 = pd.Series({'一季度': 320, '二季度': 180, '三季度': 300, '四季度': 405})
ser1, ser2

(一季度    120
 二季度    380
 三季度    250
 四季度    360
 dtype: int64,
 一季度    320
 二季度    180
 三季度    300
 四季度    405
 dtype: int64)

In [21]:
stu_names = ['狄仁杰', '白起', '李元芳', '苏妲己', '孙尚香']
cou_names = ['语文', '数学', '英语']
scores_arr = np.random.randint(60, 101, (5, 3))
df1 = pd.DataFrame(data=scores_arr, columns=cou_names, index=stu_names)
df1

语文  数学  英语
狄仁杰  69  99  60
白起   99  96  61
李元芳  65  87  89
苏妲己  70  82  65
孙尚香  93  66  74

In [25]:
df1.head(3), df1.tail(3)

(     语文  数学  英语
 狄仁杰  69  99  60
 白起   99  96  61
 李元芳  65  87  89,
      语文  数学  英语
 李元芳  65  87  89
 苏妲己  70  82  65
 孙尚香  93  66  74)

In [27]:
 df1.loc['白起'],  df1.loc['白起', '语文']

(语文    99
 数学    96
 英语    61
 Name: 白起, dtype: int32,
 np.int32(99))